### ISSUE TITLE
Issue when multiple selections are on the same line

### ISSUE THREAD

**Issue by pomdtr** [abingham/vsc-around#2]
If we have a line with two items we want to surround:

item_1 item_2 -> "item_1" "item_2"

The selection on the first word will be kept, but not the other one on the second word (who should be pushed by 3).

The issue also appear when trying to surround a word by multiple char (ex: """)

**Comment by abingham** [comment]
Wow, I have users?! Thanks for reporting this. 

I'm able to reproduce what you're seeing, and I *think* the solution is fairly straightforward. I'll see what I can do (having not looked at this code in a loooong time).

**Comment by pomdtr** [comment]
Coming from vim, a good surround operator is primordial to me (like vim-surround).
I have tested all of the extension, and i think this one is the best of the bunch.

**Comment by abingham** [comment]
I've pushed some changes that improve things. However, I'm utterly baffled by microsoft's login/identity/authorization goat rope, and I can't figure out how to publish new versions now. I'm not sure if/when I will figure it out, either.

So...feel free to try the code, and even feel free to republish it yourself if you want.

**Comment by pomdtr** [comment]
I did compile an installable vsix, i will explore how to publish it : https://send.firefox.com/download/56daf028415d7ac6/#Bcb9iIWpRk1TElOwPB_4GA

**Comment by abingham** [comment]
Ok, I've managed to publish a new version, 0.1.0. Give it a try and let me know if it works for you.

**Comment by pomdtr** [comment]
I think you can close the issue :)

**Comment by abingham** [comment]
Thanks!
